workflows:
flutter-app-workflow:
name: Flutter App Build
max_build_duration: 30
environment:
flutter: stable
scripts:
- name: Ensure Android folder
script: |
if [ ! -d "android" ]; then
flutter create . --platforms=android
fi
- name: Get dependencies
script: flutter pub get
- name: Build APK
script: flutter build apk --release
artifacts:
- build/app/outputs/flutter-apk/app-release.apk
publishing:
email:
recipients:
- ton.ndiaye.chtidiane@gmail.com
